version: "3"

services:

  db:
    build: ./mysql
    container_name: db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: p4database
      MYSQL_USER: P4user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: root

  web:
    build: ./apache
    container_name: web
    restart: always
    depends_on:
      - "db"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/www:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: p4database
      MYSQL_USER: P4user
      MYSQL_PASSWORD: password

  bind:
    image: ubuntu/bind9:latest
    container_name: bind
    restart: always
    ports:
      - "<IP-SERVEUR-ICI>:53:53/tcp"
      - "<IP-SERVEUR-ICI>:53:53/udp"
    volumes:
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/db.beesafe.co:/etc/bind/db.beesafe.co
      - ./bind9/db.reverse.beesafe.co:/etc/bind/db.reverse.beesafe.co
